Fixed tf2bd_version extraction

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -8,43 +8,28 @@ on:
       - '*.md'
 
 jobs:
-  # setup_vcpkg:
-  #   runs-on: ${{ matrix.platform.os }}
-  #   strategy:
-  #     fail-fast: true
-  #     matrix:
-  #       platform:
-  #       - os: windows-latest
-  #         triplet: x64-windows
-  #       - os: windows-latest
-  #         triplet: x86-windows
-  #   steps:
-  #   - name: Checkout
-  #     uses: actions/checkout@v2
-  #     with:
-  #       submodules: recursive
-
   setup_version:
-    # needs: setup_vcpkg
     runs-on: windows-latest
     steps:
-    # - name: Checkout
-    #   uses: actions/checkout@v2
-    #   with:
-    #     submodules: recursive
+    - name: Checkout
+      uses: actions/checkout@v2
+
     - name: Extract TF2BD_VERSION
       shell: bash
       run: |
         mkdir build_dir
         cd build_dir
-        cmake ../
+        cmake ../ || true     # we know this will fail, we just need version info from CMakeCache.txt
         TF2BD_VERSION=`cat ${{ steps.tf2bd_paths.outputs.build_dir }}/CMakeCache.txt | grep CMAKE_PROJECT_VERSION: | cut -d "=" -f2`
         echo "::set-env name=TF2BD_VERSION::$TF2BD_VERSION.${{ github.run_number }}"
+
     - name: Store TF2BD_VERSION
       uses: nick-invision/persist-action-data@v1
       with:
         data: ${{ env.TF2BD_VERSION }}
         variable: TF2BD_VERSION
+
+
 
   build:
     needs: setup_version
